### ISSUE TITLE
Installation Steps and future updates 

### ISSUE THREAD

**Issue by chrigui** [tamntn/aquagrow#1]
Hi,
first, I would like to thank you, for sharing such an amazing project.
I tried the demo and the project looks very clean and promising.

i am still not sure how i can install it on a local server if you can please share some steps.
Any Future roadmap or milestones for this project?
can a user add a growing zone (say a 4x8 ft bed and select what kind of plants are in it ?
i tried in the demo but i couldn't find anything there, even in the Garden portfolio plants and fish are not clickable to select...

many thanks.

**Comment by tamntn** [comment]
Hey, thanks for checking out the project!

To have it running on your machine, make sure you have the latest stable version of Node.js. You can just clone the repo, run ```npm install``` to install all the dependencies and run ```npm start``` to start the app.

This is currently a personal project and I only have one working prototype of the hardware system that a user needs to access all the features of the web app. There're many more things to be implemented for sure, but I will add the features to the Garden Portfolio per your request. Feel free to play around and contribute to the project by creating a PR :)

Btw, a growing zone is actually not a grow bed as you mention. It's a U.S. standard and we use it to let users know what plants will grow best at their location.
